import { Test, TestingModule } from '@nestjs/testing';
import { CommentManagerService } from '@libs/code-review/infrastructure/adapters/services/commentManager.service';
import { PARAMETERS_SERVICE_TOKEN } from '@libs/organization/domain/parameters/contracts/parameters.service.contract';
import { MessageTemplateProcessor } from '@libs/code-review/infrastructure/adapters/services/messageTemplateProcessor.service';
import { ObservabilityService } from '@libs/core/log/observability.service';
import { setLlmObservability } from '@libs/llm/llm-observability';
import { PermissionValidationService } from '@libs/ee/shared/services/permissionValidation.service';
import { CodeManagementService } from '@libs/platform/infrastructure/adapters/services/codeManagement.service';
import { FileChange } from '@libs/core/infrastructure/config/types/general/codeReview.type';
import { BehaviourForNewCommits } from '@libs/core/domain/enums/code-review.enum';

jest.mock('@libs/core/log/logger', () => ({
    createLogger: () => ({
        log: jest.fn(),
        error: jest.fn(),
        warn: jest.fn(),
        debug: jest.fn(),
        info: jest.fn(),
    }),
}));

const LLM_SUMMARY = 'New summary generated by LLM.';

function makeFile(filename: string): Partial<FileChange> {
    return {
        filename,
        patch: `${filename}_${'x'.repeat(200)}`,
        status: 'modified',
    } as Partial<FileChange>;
}

/**
 * Replacing the description used to drop the author's issue link along with
 * it, which unlinks the issue on the provider and leaves later business-logic
 * runs with no task to resolve.
 */
describe('CommentManagerService – task references survive a replaced description', () => {
    let service: CommentManagerService;
    let mockCodeManagementService: any;

    const organizationAndTeamData = {
        organizationId: 'org-123',
        teamId: 'team-456',
    };
    const repository = { id: 'repo-1', name: 'test-repo' };
    const pullRequest = {
        number: 42,
        title: 'Test PR',
        head: { ref: 'feature-branch', repo: { fullName: 'org/repo' } },
        base: { ref: 'main' },
    };

    const generate = (summaryConfig: Record<string, unknown>) =>
        service.generateSummaryPR(
            pullRequest,
            repository,
            [makeFile('a.ts')],
            organizationAndTeamData as any,
            'en-US',
            summaryConfig as any,
            undefined,
            false, // first review, not a commit run
        );

    beforeEach(async () => {
        const observability = {
            runAiSdkLLMInSpan: jest
                .fn()
                .mockImplementation(async () => ({ text: LLM_SUMMARY })),
        };
        setLlmObservability(observability as any);

        mockCodeManagementService = { getPullRequestByNumber: jest.fn() };

        const module: TestingModule = await Test.createTestingModule({
            providers: [
                CommentManagerService,
                { provide: PARAMETERS_SERVICE_TOKEN, useValue: {} },
                { provide: MessageTemplateProcessor, useValue: {} },
                { provide: ObservabilityService, useValue: observability },
                {
                    provide: PermissionValidationService,
                    useValue: {
                        validateBasicLicense: jest
                            .fn()
                            .mockResolvedValue({ allowed: true }),
                        getBYOKConfig: jest.fn().mockResolvedValue(null),
                    },
                },
                {
                    provide: CodeManagementService,
                    useValue: mockCodeManagementService,
                },
            ],
        }).compile();

        service = module.get<CommentManagerService>(CommentManagerService);
    });

    it('keeps the closing keyword when the description is replaced', async () => {
        mockCodeManagementService.getPullRequestByNumber.mockResolvedValue({
            body: 'Closes #993\n\nAdds a per-second rate limiter.',
        });

        const result = await generate({
            generatePRSummary: true,
            behaviourForExistingDescription: 'replace',
            behaviourForNewCommits: BehaviourForNewCommits.NONE,
        });

        expect(result).toContain('Closes #993');
        expect(result).toContain(LLM_SUMMARY);
        // The prose is still replaced — only the reference is carried over.
        expect(result).not.toContain('Adds a per-second rate limiter.');
    });

    it('keeps a jira-style key when the description is replaced', async () => {
        mockCodeManagementService.getPullRequestByNumber.mockResolvedValue({
            body: 'Implements PROJ-42\n\nSome prose.',
        });

        const result = await generate({
            generatePRSummary: true,
            behaviourForExistingDescription: 'replace',
            behaviourForNewCommits: BehaviourForNewCommits.NONE,
        });

        expect(result).toContain('PROJ-42');
    });

    it('replaces a description that carries no reference, as before', async () => {
        mockCodeManagementService.getPullRequestByNumber.mockResolvedValue({
            body: 'Just some prose with no task link.',
        });

        const result = await generate({
            generatePRSummary: true,
            behaviourForExistingDescription: 'replace',
            behaviourForNewCommits: BehaviourForNewCommits.NONE,
        });

        expect(result).not.toContain('Just some prose');
        expect(result).toContain(LLM_SUMMARY);
    });

    it('does not duplicate the reference when the description is concatenated', async () => {
        mockCodeManagementService.getPullRequestByNumber.mockResolvedValue({
            body: 'Closes #993\n\nAdds a per-second rate limiter.',
        });

        const result = await generate({
            generatePRSummary: true,
            behaviourForExistingDescription: 'concatenate',
            behaviourForNewCommits: BehaviourForNewCommits.NONE,
        });

        expect(result.match(/Closes #993/g)).toHaveLength(1);
        expect(result).toContain('Adds a per-second rate limiter.');
    });
});
