export enum ArtifactName {
    WithoutWaitingColumns = 'WithoutWaitingColumns',
    WorkItemSkippingWIPColumns = 'WorkItemSkippingWIPColumns',
    WIPLimit = 'WIPLimit',
    WorkItemWithClearDescription = 'WorkItemWithClearDescription',
    LeadTimeInWaitingColumns = 'LeadTimeInWaitingColumns',
    BugRatio = 'BugRatio',
    WorkItemWithAssignedOwner = 'WorkItemWithAssignedOwner',
    NewBugs = 'NewBugs',
    WorkItemsStoppedInWaitingColumns = 'WorkItemsStoppedInWaitingColumns',
    PostStartSprintInclusionsArtifact = 'PostStartSprintInclusions',
    SprintSpillover = 'SprintSpillover',
    BlockedTime = 'BlockedTime',
    HighLeadTimeInWipDeviation = 'HighLeadTimeInWipDeviation',
    PullRequestWithSizeGreaterThanLimit = 'PullRequestWithSizeGreaterThanLimit',
    CodeReviewTimeToMerge = 'CodeReviewTimeToMerge',
    HighWorkloadPerPerson = 'HighWorkloadPerPerson',
}
